#ifndef __CONSTANTS_H__
#define __CONSTANTS_H__

#define MAX_IP_ADDR_STR_LEN 40
#define DNS_QUERY_IPV4 0x01
#define DNS_QUERY_IPV6 0x02
#define DNS_QUERY_RET_FIRST 0x04

#define SUBCMD_UNKNOWN 0
#define SUBCMD_DETECT 1
#define SUBCMD_SERVER 2
#define SUBCMD_CONNECT 3
#define SUBCMD_SHUTDOWN 4

#endif